/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AWS_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BlockStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "TINYCLOUD_KEYS_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TinycloudService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "TinycloudVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}