// @generated by scripts/gen-capabilities.mjs — DO NOT EDIT.
// Source: capabilities.json (registry version 1, sha256 c9eb9392ed65ca68322a22ce07fb16e931a76aad957803515245dc7a9aff415e).
//
// Canonical single source of truth for TinyCloud capability action URNs (TC-112).
// Regenerate with: node scripts/gen-capabilities.mjs

pub const REGISTRY_VERSION: u32 = 1;
pub const REGISTRY_SOURCE_SHA256: &str =
    "c9eb9392ed65ca68322a22ce07fb16e931a76aad957803515245dc7a9aff415e";

/// Every action URN accepted at the policy boundary for `service`
/// (active, deprecated-alias, and reserved), sorted. `None` if the
/// service is unknown to the registry.
pub fn accepted_actions(service: &str) -> Option<&'static [&'static str]> {
    match service {
        "tinycloud.capabilities" => Some(&["tinycloud.capabilities/read"]),
        "tinycloud.duckdb" => Some(&[
            "tinycloud.duckdb/admin",
            "tinycloud.duckdb/export",
            "tinycloud.duckdb/import",
            "tinycloud.duckdb/read",
            "tinycloud.duckdb/select",
            "tinycloud.duckdb/write",
        ]),
        "tinycloud.encryption" => Some(&[
            "tinycloud.encryption/decrypt",
            "tinycloud.encryption/network.create",
            "tinycloud.encryption/network.revoke",
        ]),
        "tinycloud.hooks" => Some(&[
            "tinycloud.hooks/list",
            "tinycloud.hooks/register",
            "tinycloud.hooks/subscribe",
            "tinycloud.hooks/unregister",
        ]),
        "tinycloud.kv" => Some(&[
            "tinycloud.kv/del",
            "tinycloud.kv/delete",
            "tinycloud.kv/get",
            "tinycloud.kv/list",
            "tinycloud.kv/metadata",
            "tinycloud.kv/put",
        ]),
        "tinycloud.space" => Some(&[
            "tinycloud.space/create",
            "tinycloud.space/host",
            "tinycloud.space/info",
            "tinycloud.space/list",
        ]),
        "tinycloud.sql" => Some(&[
            "tinycloud.sql/admin",
            "tinycloud.sql/read",
            "tinycloud.sql/schema",
            "tinycloud.sql/select",
            "tinycloud.sql/write",
        ]),
        "tinycloud.vfs" => Some(&[
            "tinycloud.vfs/delete",
            "tinycloud.vfs/get",
            "tinycloud.vfs/list",
            "tinycloud.vfs/metadata",
            "tinycloud.vfs/put",
        ]),
        _ => None,
    }
}

/// Resolve a deprecated alias URN to its canonical URN. Returns the input
/// unchanged when it is not an alias. Aliases resolve in a single hop.
pub fn resolve_alias(action: &str) -> &str {
    match action {
        "tinycloud.duckdb/select" => "tinycloud.duckdb/read",
        "tinycloud.kv/delete" => "tinycloud.kv/del",
        "tinycloud.sql/select" => "tinycloud.sql/read",
        other => other,
    }
}

/// URNs directly implied by holding `action` (e.g. `sql/admin` implies
/// `sql/schema`). Empty slice when there are no implications.
pub fn implied_actions(action: &str) -> &'static [&'static str] {
    match action {
        "tinycloud.sql/admin" => &["tinycloud.sql/schema"],
        _ => &[],
    }
}
