use sea_orm_migration::prelude::*;

use crate::models::{
    encryption_audit, encryption_ceremony, encryption_network, encryption_network_member,
    encryption_nonce,
};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(encryption_network::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(encryption_network::Column::NetworkId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::Principal)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::Name)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::Alg)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::KeyVersion)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::PublicKey)
                            .blob()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::State)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::ThresholdN)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::ThresholdT)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::KeyBackend)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::SealedPrivateKey)
                            .blob()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::CreatedAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network::Column::UpdatedAt)
                            .string()
                            .not_null(),
                    )
                    .primary_key(Index::create().col(encryption_network::Column::NetworkId))
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(encryption_network_member::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(encryption_network_member::Column::NetworkId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network_member::Column::NodeId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network_member::Column::Role)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network_member::Column::ShareIndex)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_network_member::Column::JoinedAt)
                            .string()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .col(encryption_network_member::Column::NetworkId)
                            .col(encryption_network_member::Column::NodeId),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(encryption_ceremony::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(encryption_ceremony::Column::CeremonyId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_ceremony::Column::NetworkId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_ceremony::Column::Kind)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_ceremony::Column::State)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_ceremony::Column::TranscriptHash)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(encryption_ceremony::Column::StartedAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_ceremony::Column::CompletedAt)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(encryption_ceremony::Column::Failure)
                            .string()
                            .null(),
                    )
                    .primary_key(Index::create().col(encryption_ceremony::Column::CeremonyId))
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(encryption_nonce::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(encryption_nonce::Column::RequesterDid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_nonce::Column::Nonce)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_nonce::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .col(encryption_nonce::Column::RequesterDid)
                            .col(encryption_nonce::Column::Nonce),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(encryption_audit::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(encryption_audit::Column::RequestHash)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_audit::Column::Requester)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_audit::Column::NetworkId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_audit::Column::NodeId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_audit::Column::Outcome)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(encryption_audit::Column::DecidedAt)
                            .string()
                            .not_null(),
                    )
                    .primary_key(Index::create().col(encryption_audit::Column::RequestHash))
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(encryption_audit::Entity).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(encryption_nonce::Entity).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(encryption_ceremony::Entity).to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(encryption_network_member::Entity)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(encryption_network::Entity).to_owned())
            .await?;
        Ok(())
    }
}
