use sea_orm_migration::prelude::*;

use crate::models::{policy_challenge, policy_delegation, policy_edge, policy_issuance_audit};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(policy_delegation::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(policy_delegation::Column::DelegationCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_delegation::Column::Role)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_delegation::Column::DelegationMode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_delegation::Column::ArtifactJson)
                            .json()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_delegation::Column::NotBefore)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_delegation::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_delegation::Column::StatusCheckedAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_delegation::Column::StatusSequence)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_delegation::Column::RevokedAt)
                            .string()
                            .null(),
                    )
                    .primary_key(Index::create().col(policy_delegation::Column::DelegationCid))
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(policy_challenge::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(policy_challenge::Column::ChallengeId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_challenge::Column::ChallengeJson)
                            .json()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_challenge::Column::NonceHashHex)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_challenge::Column::IssuedAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_challenge::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_challenge::Column::ConsumedAt)
                            .string()
                            .null(),
                    )
                    .primary_key(Index::create().col(policy_challenge::Column::ChallengeId))
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(policy_issuance_audit::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(policy_issuance_audit::Column::IssuanceId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_issuance_audit::Column::SessionDelegationCid)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(policy_issuance_audit::Column::AuditJson)
                            .json()
                            .not_null(),
                    )
                    .primary_key(Index::create().col(policy_issuance_audit::Column::IssuanceId))
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                policy_issuance_audit::Entity,
                                policy_issuance_audit::Column::SessionDelegationCid,
                            )
                            .to(
                                policy_delegation::Entity,
                                policy_delegation::Column::DelegationCid,
                            ),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(policy_edge::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(policy_edge::Column::ChildCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_edge::Column::Position)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_edge::Column::ParentCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_edge::Column::EdgeKind)
                            .string()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .col(policy_edge::Column::ChildCid)
                            .col(policy_edge::Column::Position),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(policy_edge::Entity, policy_edge::Column::ChildCid)
                            .to(
                                policy_delegation::Entity,
                                policy_delegation::Column::DelegationCid,
                            ),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(policy_edge::Entity, policy_edge::Column::ParentCid)
                            .to(
                                policy_delegation::Entity,
                                policy_delegation::Column::DelegationCid,
                            ),
                    )
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(policy_edge::Entity).to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(policy_issuance_audit::Entity)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(policy_challenge::Entity).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(policy_delegation::Entity).to_owned())
            .await?;
        Ok(())
    }
}
