//! N1 protocol replay/handle state.
//!
//! This migration is deliberately a leaf.  The migration registry and model
//! registry are owned by the N4 integration lane.

use sea_orm_migration::prelude::*;

use crate::models::{
    share_anonymous_challenge, share_email_audit, share_email_quota, share_holder_read_jti,
    share_invitation_authorization_jti, share_session_handle,
};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(share_invitation_authorization_jti::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(share_invitation_authorization_jti::Column::Jti)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(
                            share_invitation_authorization_jti::Column::AuthorizationDigest,
                        )
                        .string()
                        .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_invitation_authorization_jti::Column::BindingJson)
                            .json()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_invitation_authorization_jti::Column::IssuedAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_invitation_authorization_jti::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_invitation_authorization_jti::Column::ConsumedAt)
                            .string()
                            .null(),
                    )
                    .primary_key(
                        Index::create().col(share_invitation_authorization_jti::Column::Jti),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(share_anonymous_challenge::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::ChallengeId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::RequestDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::BindingJson)
                            .json()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::OriginDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::IpDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::ShareDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::NonceHash)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::IssuedAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_anonymous_challenge::Column::ConsumedAt)
                            .string()
                            .null(),
                    )
                    .primary_key(
                        Index::create().col(share_anonymous_challenge::Column::ChallengeId),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(share_session_handle::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(share_session_handle::Column::SessionHandle)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_session_handle::Column::AuthoritySessionCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_session_handle::Column::BindingJson)
                            .json()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_session_handle::Column::HolderDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_session_handle::Column::IssuedAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_session_handle::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_session_handle::Column::RevokedAt)
                            .string()
                            .null(),
                    )
                    .primary_key(Index::create().col(share_session_handle::Column::SessionHandle))
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(share_holder_read_jti::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(share_holder_read_jti::Column::Jti)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_holder_read_jti::Column::SessionHandle)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_holder_read_jti::Column::InvocationDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_holder_read_jti::Column::BindingJson)
                            .json()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_holder_read_jti::Column::IssuedAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_holder_read_jti::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_holder_read_jti::Column::ConsumedAt)
                            .string()
                            .null(),
                    )
                    .primary_key(Index::create().col(share_holder_read_jti::Column::Jti))
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(share_email_audit::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(share_email_audit::Column::AuditId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_audit::Column::EventKind)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_audit::Column::Outcome)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_audit::Column::ShareDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_audit::Column::OriginDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_audit::Column::HolderDigest)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(share_email_audit::Column::RequestDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_audit::Column::CreatedAt)
                            .string()
                            .not_null(),
                    )
                    .primary_key(Index::create().col(share_email_audit::Column::AuditId))
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(share_email_quota::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(share_email_quota::Column::BucketKind)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_quota::Column::BucketStart)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_quota::Column::ScopeDigest)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_quota::Column::Uses)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(share_email_quota::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .col(share_email_quota::Column::BucketKind)
                            .col(share_email_quota::Column::BucketStart)
                            .col(share_email_quota::Column::ScopeDigest),
                    )
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(share_email_quota::Entity).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(share_email_audit::Entity).to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(share_holder_read_jti::Entity)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(share_session_handle::Entity).to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(share_anonymous_challenge::Entity)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(share_invitation_authorization_jti::Entity)
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
