use sea_orm_migration::prelude::*;

use crate::models::{
    policy_v3_challenge, policy_v3_registration, policy_v3_root, policy_v3_session,
};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(policy_v3_registration::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::PolicyCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::PolicyBytes)
                            .binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::PolicyDigestHex)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::OwnerDid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::PolicyRootCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::EnforcementRootCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::ContentSourceDigestHex)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::NativeProjectionHashHex)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(
                            policy_v3_registration::Column::AttestedEnforcerBindingBytes,
                        )
                        .binary()
                        .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::RegisteredAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_registration::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .primary_key(Index::create().col(policy_v3_registration::Column::PolicyCid))
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(policy_v3_root::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(policy_v3_root::Column::RootCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_root::Column::PolicyCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_root::Column::Role)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_root::Column::AuthorizationBytes)
                            .binary()
                            .not_null(),
                    )
                    .col(ColumnDef::new(policy_v3_root::Column::StatusCheckpointBytes).binary())
                    .col(
                        ColumnDef::new(policy_v3_root::Column::PreviousCheckpointDigestHex)
                            .string(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_root::Column::StatusSequence)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(policy_v3_root::Column::AdmissionEpoch)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(policy_v3_root::Column::StatusCheckedAt).string())
                    .col(ColumnDef::new(policy_v3_root::Column::StatusFreshUntil).string())
                    .col(ColumnDef::new(policy_v3_root::Column::RevokedAt).string())
                    .col(ColumnDef::new(policy_v3_root::Column::RevocationBytes).binary())
                    .primary_key(Index::create().col(policy_v3_root::Column::RootCid))
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(policy_v3_challenge::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(policy_v3_challenge::Column::ChallengeId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_challenge::Column::PolicyCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_challenge::Column::RecipientDid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_challenge::Column::NonceHashHex)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_challenge::Column::RequestedCapabilities)
                            .json()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_challenge::Column::IssuedAt)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_challenge::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(policy_v3_challenge::Column::ConsumedAt).string())
                    .primary_key(Index::create().col(policy_v3_challenge::Column::ChallengeId))
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(policy_v3_session::Entity)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(policy_v3_session::Column::SessionCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_session::Column::PolicyCid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_session::Column::AuthorizationBytes)
                            .binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_session::Column::RecipientDid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_session::Column::ClaimJti)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_session::Column::ClaimDigestHex)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_session::Column::VpDigestHex)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_session::Column::State)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_session::Column::NotBefore)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(policy_v3_session::Column::ExpiresAt)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(policy_v3_session::Column::AdmittedAt).string())
                    .primary_key(Index::create().col(policy_v3_session::Column::SessionCid))
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(policy_v3_session::Entity).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(policy_v3_challenge::Entity).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(policy_v3_root::Entity).to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(policy_v3_registration::Entity)
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
